[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
erydanos = {path = ".."}
libm = "0.2.8"
rug = "1.24.1"
rand = "0.9.0-alpha.1"

[dev-dependencies]
criterion = "0.3"
libm = "0.2.8"

[[bench]]
name = "general"
harness = false